### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: GoogleReviews\Services\Google\Clients\GoogleOAuth2Client::setToken(): Argument #1 ($token) must be of type array, string given

### ISSUE THREAD

**Issue by mustafaslk** [SidunOleh/google-reviews#1]
public function __construct()
    {
        parent::__construct();

        $this->table = "{$this->db->base_prefix}google_reviews";

        $settings = ( new Setting )->get();
        $this->googleOAuth2Client = new GoogleOAuth2Client(
            $settings[ 'client_id' ],
            $settings[ 'client_secret' ],
            $settings[ 'redirect_uri' ],
            new Client()
        );
        $this->googleOAuth2Client->setToken(
            get_option( 'google_reviews_token' )
        );
    }

Error on this line.

`
$this->googleOAuth2Client->setToken( 
            get_option( 'google_reviews_token' ) 
        );
`

[08-Jan-2024 12:48:53 UTC] PHP Fatal error:  Uncaught TypeError: GoogleReviews\Services\Google\Clients\GoogleOAuth2Client::setToken(): Argument #1 ($token) must be of type array, string given, called in /var/www/html/web/app/plugins/google-reviews/src/app/Models/GoogleReview.php on line 32 and defined in /var/www/html/web/app/plugins/google-reviews/src/app/Services/Google/Clients/GoogleOAuth2Client.php:112
Stack trace:
#0 /var/www/html/web/app/plugins/google-reviews/src/app/Models/GoogleReview.php(32): GoogleReviews\Services\Google\Clients\GoogleOAuth2Client->setToken('')
#1 /var/www/html/web/app/plugins/google-reviews/src/app/Controllers/GoogleReviewsController.php(14): GoogleReviews\Models\GoogleReview->__construct()
#2 /var/www/html/web/app/plugins/google-reviews/src/app/Core.php(32): GoogleReviews\Controllers\GoogleReviewsController->__construct()
#3 /var/www/html/web/app/plugins/google-reviews/src/app/Core.php(16): GoogleReviews\Core->ajaxActions()
#4 /var/www/html/web/app/plugins/google-reviews/google-reviews.php(45): GoogleReviews\Core->run()
#5 /var/www/html/web/wp/wp-settings.php(473): include_once('/var/www/html/w...')
#6 /var/www/html/web/wp-config.php(9): require_once('/var/www/html/w...')
#7 /var/www/html/web/wp/wp-load.php(55): require_once('/var/www/html/w...')
#8 /var/www/html/web/wp/wp-admin/admin.php(34): require_once('/var/www/html/w...')
#9 /var/www/html/web/wp/wp-admin/index.php(10): require_once('/var/www/html/w...')
#10 {main}
  thrown in /var/www/html/web/app/plugins/google-reviews/src/app/Services/Google/Clients/GoogleOAuth2Client.php on line 112

**Comment by SidunOleh** [comment]
Most likely you have incorrectly configured the project in google cloud console.
Steps:
-  make approve request(https://docs.google.com/forms/d/1XTQc-QEjsE7YrgstyJxbFDnwmhUhBFFvpNJBw3VzuuE/viewform)
-  enable Google My Business API, My Business Account Management API, My Business Business Information API
- create OAuth client ID with Authorized redirect URIs like https://your-site.com/wp-admin/admin-ajax.php?action=get_token
- set credentials in admin panel and connect

**Comment by SidunOleh** [comment]
> Most likely you have incorrectly configured the project in google cloud console. Steps:
> 
> * make approve request(https://docs.google.com/forms/d/1XTQc-QEjsE7YrgstyJxbFDnwmhUhBFFvpNJBw3VzuuE/viewform)
> * enable Google My Business API, My Business Account Management API, My Business Business Information API
> * create OAuth client ID with Authorized redirect URIs like https://your-site.com/wp-admin/admin-ajax.php?action=get_token
> * set credentials in admin panel and connect

Most likely you have incorrectly configured the project in google cloud console.
Steps:

make approve request(https://docs.google.com/forms/d/1XTQc-QEjsE7YrgstyJxbFDnwmhUhBFFvpNJBw3VzuuE/viewform)
enable Google My Business API, My Business Account Management API, My Business Business Information API
create OAuth client ID with Authorized redirect URIs like https://your-site.com/wp-admin/admin-ajax.php?action=get_token
set credentials in admin panel and connect
